### ISSUE TITLE
您好，我将源码下载到本地无法使用

### ISSUE THREAD

**Issue by 772807886** [rptec/rpvideo#3]
本地使用的PHP环境是5.6.16和7.0，都是无法正常解析，访问http://localhost/rpvideo/api/index.php?url=http://v.youku.com/v_show/id_XMTUzNzIyMjQzMg==.html 得到的结果是个空的XML（header设置了Content-Type:text/xml;charset=UTF-8，但是实际没有输出任何内容）

**Comment by alanyang** [comment]
代码只是部份吧。。防止“草根”站长拿去掉淘宝卖，要完整代码去看mama2，原理都一样
